"""create link code table

Revision ID: 2da43ca665d1
Revises: ea3cfefd5611
Create Date: 2026-09-21 20:05:05.844943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da43ca665d1'
down_revision: Union[str, Sequence[str], None] = 'ea3cfefd5611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_code',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_code_code'), 'link_code', ['code'], unique=True)
    op.create_index(op.f('ix_link_code_user_id'), 'link_code', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_code_user_id'), table_name='link_code')
    op.drop_index(op.f('ix_link_code_code'), table_name='link_code')
    op.drop_table('link_code')
    # ### end Alembic commands ###
