"""create user_sandbox table

Revision ID: 886de26d100e
Revises: 
Create Date: 2026-09-15 20:04:16.662088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886de26d100e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sandbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('box_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('machine_type', sa.String(), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('box_id')
    )
    op.create_index(op.f('ix_user_sandbox_is_active'), 'user_sandbox', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_sandbox_user_id'), 'user_sandbox', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sandbox_user_id'), table_name='user_sandbox')
    op.drop_index(op.f('ix_user_sandbox_is_active'), table_name='user_sandbox')
    op.drop_table('user_sandbox')
    # ### end Alembic commands ###
