"""create permission rule table

Revision ID: a0fc8f4f82e5
Revises: 9f2a6e1c8b41
Create Date: 2026-09-29 12:45:58.708082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0fc8f4f82e5'
down_revision: Union[str, Sequence[str], None] = '9f2a6e1c8b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_rule',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('connector', sa.String(), nullable=True),
    sa.Column('tool', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_rule_bucket'), 'permission_rule', ['bucket'], unique=False)
    op.create_index('ix_permission_rule_lookup', 'permission_rule', ['user_id', 'bucket', 'connector', 'tool'], unique=False)
    op.create_index(op.f('ix_permission_rule_user_id'), 'permission_rule', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_rule_user_id'), table_name='permission_rule')
    op.drop_index('ix_permission_rule_lookup', table_name='permission_rule')
    op.drop_index(op.f('ix_permission_rule_bucket'), table_name='permission_rule')
    op.drop_table('permission_rule')
    # ### end Alembic commands ###
