"""add permission_ask table

Revision ID: d2fc641cb3d1
Revises: a0fc8f4f82e5
Create Date: 2026-10-05 13:14:13.273608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fc641cb3d1'
down_revision: Union[str, Sequence[str], None] = 'a0fc8f4f82e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_ask',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('connector', sa.String(), nullable=True),
    sa.Column('tool', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('always', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='fk_permission_ask_task_id_task'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_ask_status'), 'permission_ask', ['status'], unique=False)
    op.create_index(op.f('ix_permission_ask_task_id'), 'permission_ask', ['task_id'], unique=False)
    op.create_index(op.f('ix_permission_ask_user_id'), 'permission_ask', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_ask_user_id'), table_name='permission_ask')
    op.drop_index(op.f('ix_permission_ask_task_id'), table_name='permission_ask')
    op.drop_index(op.f('ix_permission_ask_status'), table_name='permission_ask')
    op.drop_table('permission_ask')
    # ### end Alembic commands ###
