"""add task session_id

Revision ID: e2ee182c04a0
Revises: 2da43ca665d1
Create Date: 2026-09-22 10:29:39.996455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ee182c04a0'
down_revision: Union[str, Sequence[str], None] = '2da43ca665d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_task_session_id'), 'task', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_session_id'), table_name='task')
    op.drop_column('task', 'session_id')
    # ### end Alembic commands ###
